baremetal: imx93: change back the mkimage type to imximage
Error: u-boot-dtb.cfgout[45] - Invalid command (IMAGE_VERSION)
make[1]: *** [arch/arm/mach-imx/Makefile:209: u-boot-dtb.imx] Error 1
make[1]: *** Deleting file 'u-boot-dtb.imx'
make: *** [Makefile:1254: u-boot-dtb.imx] Error 2

Introduced by f637dfe8c468 ("mach-imx: Add i.MX93 binman support.")

Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@nxp.com>