driver: irqchip: use PHASE_ instead of XPL_ in Makefile
Fixed build issue on imx8mm baremetal master defconfig:
arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/13.2.1/../../../../aarch64-none-linux-gnu/bin/ld: /tmp/ccdQP0zV.ltrans0.ltrans.o: in function `gicv3_probe':
real-time-edge-uboot/spl/../drivers/irqchip/irq-gic-v3.c:171:(.text.gicv3_probe+0x14): undefined reference to `dev_get_priv'
arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/13.2.1/../../../../aarch64-none-linux-gnu/bin/ld: /tmp/ccdQP0zV.ltrans0.ltrans.o: in function `gicv3_probe':
real-time-edge-uboot/spl/../include/dm/read.h:996:(.text.gicv3_probe+0x24): undefined reference to `devfdt_get_addr_index'
arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/13.2.1/../../../../aarch64-none-linux-gnu/bin/ld: real-time-edge-uboot/spl/../include/dm/read.h:996:(.text.gicv3_probe+0x60): undefined reference to `devfdt_get_addr_index'
collect2: error: ld returned 1 exit status
make[1]: *** [scripts/Makefile.xpl:546: spl/u-boot-spl] Error 1
make: *** [Makefile:2440: spl/u-boot-spl] Error 2

Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@nxp.com>