baremetal: ls1021aiot: slave: fix build issue
These lines have been removed by the following 2 upstream commits:
c4594242aafc ("led: remove support for red LED in legacy API")
c31f51d502af ("led: remove coloured_LED_init, yellow and blue status LEDs in legacy API")

Error logs:
arm-none-linux-gnueabihf-ld: arch/arm/lib/crt0.o: in function `secondary_main_entry':
real-time-edge-uboot/arch/arm/lib/crt0.S:304:(.text+0xe4): undefined reference to `coloured_LED_init'
arm-none-linux-gnueabihf-ld: real-time-edge-uboot/arch/arm/lib/crt0.S:305:(.text+0xe8): undefined reference to `red_led_on'

Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@nxp.com>